# Generated by Django 4.0.6 on 2023-09-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=50)),
                ('request_type', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete'), ('head', 'head'), ('options', 'options'), ('trace', 'trace')], default='get', max_length=7)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('api_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruction.apipath')),
            ],
            options={
                'ordering': ['api_path', 'id'],
            },
        ),
    ]
