# Generated by Django 4.0.6 on 2023-09-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReferrer',
            fields=[
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_referral', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referrer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['referrer', 'referral'],
            },
        ),
    ]
